[k8s]
10.100.2.5 ansible_user=root ansible_password=BeforeDeskDeath59 ansible_ssh_common_args='-o StrictHostKeyChecking=no'
kubexmaster.ithpharma.local ansible_user=root ansible_password=BlueDragon1339954 ansible_ssh_common_args='-o StrictHostKeyChecking=no'